version: "3.8"

services:
  suma-app:
    image: abelharo2/trd-app:latest
    ports:
      - "8080:8080"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
