name: CI Pipeline

on:
  push:
    branches: ["main"] # Solo se ejecuta en commits a la rama main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x] # Aquí puedes definir las versiones de Node.js que quieres usar en la matriz

    steps:
      # Checkout del repositorio
      - uses: actions/checkout@v3

      # Configuración de Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Instalación de dependencias y ejecución de tests
      - run: npm install
      - run: npm run build --if-present
      - run: npm test

  build-and-push:
    runs-on: ubuntu-latest
    needs: test # Este job se ejecuta solo si 'test' pasa correctamente
    if: github.ref == 'refs/heads/main' # Condición: Solo se ejecuta si el commit es en la rama main

    steps:
      # Checkout del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Login a Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construcción de la imagen de Docker
      - name: Build Docker image
        run: docker build -t abelharo2/trd-app:latest .

      # Subir la imagen a Docker Hub
      - name: Push Docker image
        run: docker push abelharo2/trd-app:latest
